"""
MergekitBackend — generate and execute mergekit configs from a GrowthPlan.

mergekit (https://github.com/arcee-ai/mergekit) handles the heavy lifting of
copying and merging model weights on-disk without loading the full model into
RAM. foundry generates the YAML; mergekit executes it.

SOLAR passthrough in mergekit:
  The grown model is constructed by listing "slices" — contiguous ranges of
  transformer layers from the seed model, in the order they appear in the
  grown model. Each unique consecutive run in ``layer_map`` becomes one slice.

M4 scope:
  - ``growth_plan_to_mergekit_yaml()``  — pure config generation (no mergekit needed)
  - ``save_mergekit_config()``          — write YAML to disk
  - ``run_merge()``                     — requires mergekit; raises gracefully if missing

Example generated YAML for layer_map [0,1,2,3, 0,1,2,3] (4→8 SOLAR double)::

    merge_method: passthrough
    slices:
      - sources:
          - model: /path/to/seed
            layer_range: [0, 4]
      - sources:
          - model: /path/to/seed
            layer_range: [0, 4]
    dtype: bfloat16
"""
from __future__ import annotations

from pathlib import Path
from typing import Any

from foundry.growth.planner import GrowthPlan


# ── Layer-map → mergekit slices ────────────────────────────────────────────

def _layer_map_to_slices(layer_map: list[int], seed_path: str) -> list[dict]:
    """
    Convert a foundry layer_map to mergekit slice definitions.

    Consecutive ascending runs in layer_map become a single slice.
    Discontinuities (duplicated or skipped source layers) start a new slice.

    Example:
        [0,1,2,3, 2,3,4,5] → [{[0,4]}, {[2,6]}]
        [0,0,1,2,3,3]       → [{[0,1]}, {[0,4]}, {[3,4]}]
    """
    slices: list[dict] = []
    i = 0
    while i < len(layer_map):
        start = layer_map[i]
        j = i + 1
        while j < len(layer_map) and layer_map[j] == layer_map[j - 1] + 1:
            j += 1
        end = layer_map[j - 1] + 1   # exclusive end
        slices.append({
            "sources": [{"model": seed_path, "layer_range": [start, end]}]
        })
        i = j
    return slices


# ── Config generation ──────────────────────────────────────────────────────

def growth_plan_to_mergekit_yaml(
    plan:      GrowthPlan,
    seed_path: str,
    dtype:     str = "bfloat16",
) -> dict:
    """
    Convert a GrowthPlan into a mergekit configuration dict.

    Uses mergekit's ``passthrough`` merge method: each slice is a contiguous
    range of transformer layers copied verbatim from the seed model.
    No interpolation, no blending — pure SOLAR duplicate-and-trim.

    Args:
        plan:      GrowthPlan produced by ``plan_growth()``.
        seed_path: Local path or HF model ID of the seed model.
        dtype:     Weight dtype for the output (default bfloat16).

    Returns:
        Dict suitable for ``yaml.dump()``.
    """
    slices = _layer_map_to_slices(plan.layer_map, seed_path)
    cfg: dict[str, Any] = {
        "merge_method": "passthrough",
        "slices":       slices,
        "dtype":        dtype,
    }
    if plan.shape_warning:
        cfg["_foundry_shape_warning"] = plan.shape_warning
    cfg["_foundry_note"] = (
        f"Generated by olaverse-foundry. "
        f"SOLAR-style {plan.src_layers}→{plan.target_layers} layer upscale "
        f"({plan.scale_factor:.2f}×). Heal with distillation before use."
    )
    return cfg


def save_mergekit_config(
    plan:        GrowthPlan,
    seed_path:   str,
    output_path: str | Path,
    dtype:       str = "bfloat16",
) -> Path:
    """
    Write a mergekit YAML config to disk.

    Args:
        plan:        GrowthPlan.
        seed_path:   Seed model path or HF ID.
        output_path: Destination .yaml file path.
        dtype:       Output dtype.

    Returns:
        Path to the written file.
    """
    try:
        import yaml
    except ImportError:
        raise ImportError(
            "PyYAML is required. Install with: pip install olaverse-foundry"
        )
    cfg  = growth_plan_to_mergekit_yaml(plan, seed_path, dtype=dtype)
    path = Path(output_path)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(yaml.dump(cfg, default_flow_style=False, sort_keys=False))
    return path


# ── Execution ──────────────────────────────────────────────────────────────

def run_merge(
    plan:        GrowthPlan,
    seed_path:   str,
    output_dir:  str | Path,
    config_path: str | Path | None = None,
    dtype:       str = "bfloat16",
    backend:     str = "native",
) -> Path:
    """
    Materialise the SOLAR-upscaled model on disk.

    Two backends:

    * ``backend="native"`` (default) — uses transformers + foundry's own
      :func:`build_upscaled_state_dict`. No mergekit required. Loads the seed,
      rebuilds it at the grown depth, copies the duplicated layers, and saves a
      standard HF directory. Also writes the mergekit YAML for reference.
    * ``backend="mergekit"`` — delegates to mergekit's passthrough merge
      (streams weights from disk; lower RAM for very large seeds).

    The output is a standard HF model directory loadable with
    ``AutoModelForCausalLM.from_pretrained(output_dir)``.

    Args:
        plan:        GrowthPlan from ``plan_growth()``.
        seed_path:   Seed model path or HF model ID.
        output_dir:  Directory to write the grown model.
        config_path: Optional path to a pre-written mergekit YAML (mergekit backend).
        dtype:       Output weight dtype.
        backend:     "native" (default) or "mergekit".

    Returns:
        Path to the output directory.

    Example::

        from foundry import plan_growth
        from foundry.contracts import ArchConfig
        from foundry.growth.mergekit_backend import run_merge

        cfg  = ArchConfig(n_layers=32, d_model=4096, vocab_size=32000)
        plan = plan_growth(cfg, to_params=15e9)
        run_merge(plan, "meta-llama/Llama-3.1-8B", "./grown_15b")   # no mergekit needed
    """
    output_dir = Path(output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    # Always write the mergekit YAML alongside the output for reproducibility.
    save_mergekit_config(plan, seed_path, output_dir / "mergekit_config.yaml", dtype=dtype)

    if backend == "native":
        return _run_merge_native(plan, seed_path, output_dir, dtype=dtype)
    if backend == "mergekit":
        return _run_merge_mergekit(plan, seed_path, output_dir, config_path, dtype=dtype)
    raise ValueError(f"Unknown backend {backend!r}. Use 'native' or 'mergekit'.")


def _torch_dtype(dtype: str):
    import torch
    return {
        "bfloat16": torch.bfloat16,
        "float16":  torch.float16,
        "float32":  torch.float32,
    }.get(dtype, torch.bfloat16)


def _run_merge_native(
    plan:       GrowthPlan,
    seed_path:  str,
    output_dir: Path,
    dtype:      str = "bfloat16",
) -> Path:
    """SOLAR passthrough merge using transformers + build_upscaled_state_dict."""
    try:
        import torch  # noqa: F401
        from transformers import AutoConfig, AutoModelForCausalLM, AutoTokenizer
    except ImportError:
        raise ImportError(
            "transformers + torch are required for the native merge backend. "
            "Install with: pip install olaverse-foundry[torch]"
        )

    from foundry.growth.planner import build_upscaled_state_dict

    td = _torch_dtype(dtype)
    seed_model = AutoModelForCausalLM.from_pretrained(seed_path, torch_dtype=td)
    new_state  = build_upscaled_state_dict(seed_model.state_dict(), plan.layer_map)

    grown_cfg = AutoConfig.from_pretrained(seed_path)
    grown_cfg.num_hidden_layers = plan.target_layers

    grown = AutoModelForCausalLM.from_config(grown_cfg).to(td)
    missing, unexpected = grown.load_state_dict(new_state, strict=False)
    if unexpected:
        raise RuntimeError(
            f"Native merge produced {len(unexpected)} unexpected keys "
            f"(first: {unexpected[:3]}). Layer prefix may differ for this "
            "architecture — fall back to backend='mergekit'."
        )

    grown.save_pretrained(str(output_dir))
    try:
        AutoTokenizer.from_pretrained(seed_path).save_pretrained(str(output_dir))
    except Exception:
        pass  # not all seeds ship a tokenizer; the model dir is still valid
    return output_dir


def _run_merge_mergekit(
    plan:        GrowthPlan,
    seed_path:   str,
    output_dir:  Path,
    config_path: str | Path | None = None,
    dtype:       str = "bfloat16",
) -> Path:
    """Delegate to mergekit's passthrough merge (streams weights from disk)."""
    try:
        import mergekit  # noqa: F401
    except ImportError:
        raise ImportError(
            "mergekit is required for backend='mergekit'. "
            "Install with: pip install olaverse-foundry[merge] "
            "(or use the default backend='native', which needs no mergekit)."
        )
    try:
        import yaml
    except ImportError:
        raise ImportError("PyYAML is required. Install with: pip install olaverse-foundry")

    if config_path is None:
        config_path = output_dir / "mergekit_config.yaml"
        save_mergekit_config(plan, seed_path, config_path, dtype=dtype)

    raw_cfg = yaml.safe_load(Path(config_path).read_text())
    for k in list(raw_cfg.keys()):       # strip foundry-only metadata
        if k.startswith("_foundry"):
            del raw_cfg[k]

    from mergekit.config.main import MergeConfiguration
    from mergekit.merge import MergeOptions, run_merge as _mergekit_run

    merge_cfg = MergeConfiguration.model_validate(raw_cfg)
    options   = MergeOptions(
        out_path=str(output_dir),
        cuda=False,
        copy_tokenizer=True,
        low_cpu_memory=True,
    )
    _mergekit_run(merge_cfg, str(output_dir), options=options)
    return output_dir
